services:
  
  db-product:
    image: 'mysql:8'
    container_name: db-product
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userDb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_product_data:/var/lib/mysql
    networks:
      shared:
  

  db-order:
    image: 'mysql:8'
    container_name: db-order
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orderDb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - db_order_data:/var/lib/mysql
    networks:
      shared:
  
 

volumes:
#  ecom_auth_api_data:
#  ecom_payment_api_data:
  db_product_data:
  db_order_data: