// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Order.API.Data;

#nullable disable

namespace Order.API.Migrations
{
    [DbContext(typeof(OrderDBContext))]
    [Migration("20250904182036_InitialCase")]
    partial class InitialCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Order.API.Data.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25430aac-71eb-4686-8a51-bcc396fcb4f6"),
                            CustomerEmail = "rairacer@gmail",
                            OrderDate = new DateTime(2025, 9, 4, 20, 20, 35, 736, DateTimeKind.Local).AddTicks(8902),
                            OrderStatus = "Pending Payment"
                        });
                });

            modelBuilder.Entity("Order.API.Data.SingleItemOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SingleItemOrders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10fb6988-3b05-41bf-b66e-45fba6e38df0"),
                            ParentId = new Guid("25430aac-71eb-4686-8a51-bcc396fcb4f6"),
                            ProductId = new Guid("00a97beb-e222-4b1e-a303-64d415fcb1eb"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("9d48eb2a-10b7-437f-a4cb-2ede05fdddb6"),
                            ParentId = new Guid("25430aac-71eb-4686-8a51-bcc396fcb4f6"),
                            ProductId = new Guid("4ac5caf5-8151-48c7-a07a-9ec3a19cf510"),
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("Order.API.Data.SingleItemOrder", b =>
                {
                    b.HasOne("Order.API.Data.OrderModel", "Parent")
                        .WithMany("OrderItemList")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Order.API.Data.OrderModel", b =>
                {
                    b.Navigation("OrderItemList");
                });
#pragma warning restore 612, 618
        }
    }
}
